version: "3.8"
services:
  face_recognition_service:
    container_name: face_recognition_service
    image: face_recognition_service:latest
    build:
       context: .
       dockerfile: docker/Dockerfile
    volumes:
      - .:/face_recognition_service
    ports:
      - "8000:8000"
    command: ["python3", "-m", "uvicorn", "src.main:app", "--host=0.0.0.0", "--port=8000"]